apiVersion: v1
kind: Secret
metadata:
  name: web-app
type: Opaque
data:
  db-user: c2thZGktd2Vi
  db-password: V3VVRkxmeSFhMkxwUnhveGVVUFg5X0VK
  cookie-salt: ZGJmYjlhNTQ3OTZiYTk2M2ZhMjk5MjgzMjY5MGZhNjkwZDM1ZDIzNjFjMjQ0OWUxNzgzODE1NjkyYjQ2MGRlYTA2NGM5YThkMTMzYzJhY2NmZDRlMGE1YjVlY2ZjZjZiYzIyNzQwZWQyYWM3NWRkNTE2NzY1MzkzODE0Njg2ZDQ=
  github-secret: ODhhYzU2NDNmNDczODZkNWEwYTdkMWFmYmI4NjI2OWQxMmQ5YjUyMQ==
  github-id: MmU0MmNiYjQ5ZTFlZjU3YWUwZGI=