# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: deploy to staging

on:
  push:
    branches: [ staging ]


jobs:
  build:

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: skadi
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v6.0.1
        with:
          submodules: recursive
          #token: ${{ secrets.CLONE_PAT }}
      - uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-new-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-new-
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          SQL_PASSWORD: mysecretpassword
          SQL_USER: postgres
          SQL_DB: skadi
          SQL_HOST: "localhost:5432"
          GITHUB_SECRET: ${{ secrets.OAUTH_SECRET }}
          GITHUB_ID: ${{ secrets.OAUTH_ID }}
          COOKIE_SALT: ${{ secrets.COOKIE_SALT }}
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results
          path: web/build/reports
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: rg.nl-ams.scw.cloud/staging-skadi-cloud
          username: nologin
          password: ${{ secrets.STAGING_SCALEWAY_TOKEN_DOCKER }}
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v5.10.0
        with:
          images: rg.nl-ams.scw.cloud/staging-skadi-cloud/web
          tags: |
            type=sha

      - name: Build with installDist
        run: ./gradlew :web:installDist
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: build docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: release=${{ steps.vars.outputs.tag }}

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.STAGING_KUBECONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        id: setcontext
      - uses: azure/k8s-create-secret@v5
        with:
          namespace: 'default'
          secret-type: 'generic'
          arguments: --from-literal=db-user=skadi --from-literal=cookie-salt=${{ secrets.COOKIE_SALT }} --from-literal=db-password=${{ secrets.STAGING_DB_PASSWORD }} --from-literal=github-secret=${{ secrets.STAGING_GITHUB_SECRET }} --from-literal=github-id=${{ secrets.STAGING_GITHUB_ID }}
          secret-name: web-app
      - uses: azure/k8s-create-secret@v5
        with:
          namespace: 'kube-system'
          secret-type: 'generic'
          arguments: --from-literal=token=${{ secrets.STAGING_SCALEWAY_TOKEN }}
          secret-name: scw-dns-token
      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v5
        with:
          namespace: 'default'
          container-registry-url: 'rg.nl-ams.scw.cloud'
          container-registry-username: nologin
          container-registry-password: ${{ secrets.STAGING_SCALEWAY_TOKEN_DOCKER }}
          secret-name: registry-secret

      - uses: Azure/k8s-deploy@v5
        with:
          namespace: kube-system
          manifests: |
            kubernetes/common/traefik/01_crd.yml
            kubernetes/common/traefik/02_volume.yml
            kubernetes/staging/traefik/03_deployment.yml
          imagepullsecrets: |
            registry-secret

      - uses: Azure/k8s-deploy@v5
        with:
          images: 'rg.nl-ams.scw.cloud/staging-skadi-cloud/web:${{ steps.meta.outputs.version }}'
          manifests: |
            kubernetes/common/web/01_roles.yml
            kubernetes/staging/web/02_deployment.yml
            kubernetes/staging/web/03_ingress.yml
          imagepullsecrets: |
            registry-secret

